stages:
  - coverage

coverage:
  stage: coverage
  image: python:3
  script:
    - pip install pytest pytest-cov
    
    # Run pytest with coverage but without executing tests
    - pytest --cov --cov-report term --cov-report xml:coverage.xml --ignore=test/

  # Specifying coverage regex for GitLab to recognize coverage results
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

  # Declaring artifacts to be stored, including the coverage.xml file
  artifacts:
    paths:
      - coverage.xml
