stages:
  - test

test:
  stage: test
  image: python:3
  script:
    - pip install pytest pytest-cov
    # No need to run pytest with coverage, just install the dependencies
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    reports:
      junit: test/test-reports/TEST-ApiTest-20240503121624.xml
      coverage: test/coverage.xml
