# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- analyze
- deploy
test:
  stage: test
  image: python:3
  script:
  - pip install pytest-mock
  - pip install requests pytest pytest-cov
  - pytest --cov --cov-report term --cov-report xml:coverage.xml
  coverage: "/TOTAL.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/"
  artifacts:
    reports:
      junit: test/test/report.xml
    paths:
    - test/coverage.xml
sonarcloud-analysis:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint:
    - ''
  cache:
    key: "${CI_JOB_NAME}"
    paths:
    - ".sonar/cache"
  script:
  - sonar-scanner -Dsonar.sources=src/,run.py,test/newspaper_test.py, -Dsonar.organization=gitaction-poc7-sonarqube
    -Dsonar.projectKey=gitaction-poc7-sonarqube_python-ci-3-tier-backend   -Dsonar.python.coverage.reportPaths=coverage.xml
slack_notification:
  stage: deploy
  script:
  - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Python Application
    Deployed Successfully! \U0001F680\"}' https://hooks.slack.com/services/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\n"
include:
- template: Security/Secret-Detection.gitlab-ci.yml
