stages:
  - build
  - test
  - analyze
  - trivy_scan
  - synk_scan
  - docker_scan
  - deploy
  - notify

# variables:
  # ARTIFACTORY_URL: "https://onkarko.jfrog.io/artifactory/python_3_tier-pypi-local/"
  # ARTIFACTORY_REPO: "python_3_tier-pypi-local"
  # DOCKER_IMAGE: "python_ci_image"
  # DOCKER_TAG: "v2"
  # DOCKER_REGISTRY: $CI_REGISTRY
  # DOCKER_USER: $CI_REGISTRY_USER
  # DOCKER_PASSWORD: $DOCKER_CI_TOKEN
  # GITLAB_ACCESS_TOKEN: $GITLAB_PERSONAL_TOKEN

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml


code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.html]
